Release 4.3.0

diff --git a/scripts/pslug b/scripts/pslug
--- a/scripts/pslug
+++ b/scripts/pslug
@@ -2,30 +2,16 @@
 
 # Script to get the plugin slug from composer.json file.
 
-# Set the SOURCE_PATH variable to the current directory or use the passed argument.
 SOURCE_PATH=${1:-$(pwd)}
+COMPOSER_FILE="${SOURCE_PATH}/composer.json"
 
-# Show the usage information.
 usage() {
     echo "Usage: pslug [source_path]"
-    echo ""
-    echo "source_path: The path to the source code of the plugin."
-    echo "             Default: The current directory."
+    echo "source_path: Path to the plugin source code. Default: Current directory."
 }
 
-# Check if the usage information should be displayed.
-if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
-    usage
-    exit 0
-fi
+[[ "$1" == "--help" || "$1" == "-h" ]] && { usage; exit 0; }
 
-# Check if the composer.json file exists in the source path.
-if [ ! -f "${SOURCE_PATH}/composer.json" ]; then
-    echo "The composer.json file does not exist in the source path."
-    echo ""
-    echo "Source path: ${SOURCE_PATH}"
-    exit 1
-fi
+[[ ! -f "$COMPOSER_FILE" ]] && { echo "Error: composer.json not found in ${SOURCE_PATH}"; exit 1; }
 
-# Get the plugin name from the composer.json file.
-parsejson "${SOURCE_PATH}/composer.json" "extra.plugin-slug"
+parsejson "$COMPOSER_FILE" "extra.plugin-slug"
